### PR TITLE
Selectable group

### LINKED ISSUE #282: Searchable server side tags clears ngmodel on search
Please fill below information if issuing a bug report. 
### Expected behaviour
My old selected values should have been retained in select area

### Actual behaviour
Tags are loaded from server side, using code from examples. I search for tag select some. Then i research it clear my model values.

### PR DESCRIPTION
**Pull request by anjmao**
fixes #282

### CODE REVIEW

File: src/ng-select/ng-select.component.ts [hunk 1]
```diff
@@ -84,9 +87,10 @@ export class NgSelectComponent implements OnDestroy, OnChanges, AfterViewInit, C
     @Input() groupBy: string;
     @Input() bufferAmount = 4;
     @Input() virtualScroll = false;
+    @Input() allowSelectGroup = false;
```
Comment (varnastadeus) [inline src/ng-select/ng-select.component.ts]: `groupSelectable`. Update docs
